version: "3"
services:
  web:
    build: 
      context: .
      target: backend
    ports: ['5000:5000']
    volumes: ['.:/app']
    environment:
      FLASK_DEBUG: 1
  frontend:
    build: 
      context: .
      target: frontend
    ports: ['5173:5173']
    volumes: 
      - './frontend:/app'
      - exclude:/app/node_modules/
volumes:
  exclude:
